In [1]:
%matplotlib notebook 
import sys
sys.path.append('../')
import matplotlib.pyplot as plt
from rdkit import Chem
from rdkit.Chem import Draw

import numpy as np
import blackout_utils as bu

import torch

In [2]:
def draw_step(tokens):
    tokens = list( tokens.detach().numpy() )
    smiles = tokenizer.decode(tokens,skip_special_tokens=True,
                             clean_up_tokenization_spaces=True).replace(' ','')
    try:
        molecule = Chem.MolFromSmiles(smiles)
        im = Draw.MolToImage(molecule)
    except:
        im = [[]]
    ax[0].imshow(im)
    ax[0].axis('off')
    ax[1].text(0,.5,smiles)
    ax[1].axis('off')
    ax[2].text(0,.5, tokens[:6])
    ax[2].text(0,.25, tokens[6:])

    ax[2].axis('off')

In [8]:
smiles = 'C1=CC2NC3(C1)COC23'
tokenizer = bu.get_tokenizer('../../etc/tokenizers/regex', tokenizer_type='regex')
tokenized_smiles = tokenizer(smiles)
molecule = Chem.MolFromSmiles(smiles)

# plot using RDKit 
im = Draw.MolToImage(molecule)
# f,ax = plt.subplots(1,3, figsize=(7,2) )
# draw_step(tokenized_smiles['input_ids'])


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [3]:
from importlib import reload

In [4]:
schedule = bu.get_binomial_corrupter('../schedules/binomial_corrupter_files.npz')

In [29]:
times = schedule['observation_times'][:500]

In [32]:
reload(bu)
tokens = np.array(tokenized_smiles['input_ids'])[:-1][1:]
tokens = torch.LongTensor(tokens)
for i,t in enumerate(times): 
    cdf = schedule['noise_cdf'][int(i),:,tokens.long()]
    u = torch.Tensor(np.random.rand(len(tokens)))
    tokens = torch.argmax((u<cdf).long(),dim=0).int()
    # print(list(tokens.detach().numpy()))
    print(tokenizer.decode(tokens.detach().numpy()).replace(' ',''))

C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1)COC23
C1=CC2NC3(C1

In [28]:
times

tensor([3.0590e-07])

In [18]:
tokenized_smiles

{'input_ids': [73, 1, 8, 6, 1, 1, 10, 9, 1, 12, 3, 1, 8, 4, 1, 5, 1, 10, 12, 71], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [4]:
from importlib import reload

In [46]:
# train
reload(bu)
model, train, val = bu.main()

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


max value (train): 73
max value (val): 73
support size (train): 12
EPOCH 1:
  batch 32 loss: 0.0020001610882900422
LOSS train 0.0020001610882900422 valid -0.012039422988891602
EPOCH 2:
  batch 32 loss: -0.04967730067437515
LOSS train -0.04967730067437515 valid -0.05025565251708031
EPOCH 3:
  batch 32 loss: -0.09211504936683923
LOSS train -0.09211504936683923 valid -0.08883728832006454
EPOCH 4:
  batch 32 loss: -0.13181275804527104
LOSS train -0.13181275804527104 valid -0.12018077075481415
EPOCH 5:
  batch 32 loss: -0.17221287917345762
LOSS train -0.17221287917345762 valid -0.15872429311275482
EPOCH 6:
  batch 32 loss: -0.20526105165481567
LOSS train -0.20526105165481567 valid -0.18097388744354248
EPOCH 7:
  batch 32 loss: -0.24569050129503012
LOSS train -0.24569050129503012 valid -0.1815953105688095
EPOCH 8:
  batch 32 loss: -0.24114263663068414
LOSS train -0.24114263663068414 valid -0.21831686794757843
EPOCH 9:
  batch 32 loss: -0.2666746834293008
LOSS train -0.2666746834293008 valid 

  batch 32 loss: -0.32316524954512715
LOSS train -0.32316524954512715 valid -0.2814803719520569
EPOCH 79:
  batch 32 loss: -0.3003735411912203
LOSS train -0.3003735411912203 valid -0.39322781562805176
EPOCH 80:
  batch 32 loss: -0.31241610646247864
LOSS train -0.31241610646247864 valid -0.25434964895248413
EPOCH 81:
  batch 32 loss: -0.3529714569449425
LOSS train -0.3529714569449425 valid -0.2580239772796631
EPOCH 82:
  batch 32 loss: -0.3407957307063043
LOSS train -0.3407957307063043 valid -0.23905225098133087
EPOCH 83:
  batch 32 loss: -0.3214706829749048
LOSS train -0.3214706829749048 valid -0.410305917263031
EPOCH 84:
  batch 32 loss: -0.3163570291362703
LOSS train -0.3163570291362703 valid -0.2358168661594391
EPOCH 85:
  batch 32 loss: -0.32930954173207283
LOSS train -0.32930954173207283 valid -0.2743777632713318
EPOCH 86:
  batch 32 loss: -0.3174622296355665
LOSS train -0.3174622296355665 valid -0.269972026348114
EPOCH 87:
  batch 32 loss: -0.3173729460686445
LOSS train -0.317372

  batch 32 loss: -0.34838586673140526
LOSS train -0.34838586673140526 valid -0.24811257421970367
EPOCH 157:
  batch 32 loss: -0.3302175719290972
LOSS train -0.3302175719290972 valid -0.2722477316856384
EPOCH 158:
  batch 32 loss: -0.3403393542394042
LOSS train -0.3403393542394042 valid -0.23737573623657227
EPOCH 159:
  batch 32 loss: -0.348624917678535
LOSS train -0.348624917678535 valid -0.2352290004491806
EPOCH 160:
  batch 32 loss: -0.3125040396116674
LOSS train -0.3125040396116674 valid -0.2599751949310303
EPOCH 161:
  batch 32 loss: -0.30474253045395017
LOSS train -0.30474253045395017 valid -0.26619940996170044
EPOCH 162:
  batch 32 loss: -0.3146246140822768
LOSS train -0.3146246140822768 valid -0.2606392204761505
EPOCH 163:
  batch 32 loss: -0.31058971397578716
LOSS train -0.31058971397578716 valid -0.24273799359798431
EPOCH 164:
  batch 32 loss: -0.3168306821025908
LOSS train -0.3168306821025908 valid -0.2504273056983948
EPOCH 165:
  batch 32 loss: -0.3142413734458387
LOSS train

In [49]:
import sys
sys.path.append('../')
import simple_model as sm
reload(bu)
reload(sm)

schedule = bu.get_binomial_corrupter('../schedules/binomial_corrupter_files.npz')

# model = sm.ConvNet(20, 75)
# model.load_state_dict(torch.load('../models/20230516_133516/model_10'))

_,all_mol = bu.generate_molecule(model, schedule, True)


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 68 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 33 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 49 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 60 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 66 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 69 tensor(9.3277e-09)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 te

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 45 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 55 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 62 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 64 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 71 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 74 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(2.9194e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 te

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(9.4168e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(9.4168e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(9.4168e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(9.4168e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 75 tensor(9.7036e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 58 tensor(9.7036e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 29 tensor(9.7036e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 48 tensor(9.7036e-08)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 42 te

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 68 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 68 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 69 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 70 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 70 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 69 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 68 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 69 tensor(3.2256e-07)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 70 te

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 54 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 60 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 61 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 61 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 61 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 62 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 63 tensor(1.0722e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 64 te

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 55 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 57 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 55 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(3.5638e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 56 tensor(3.6725e-06)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 42 te

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 44 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 47 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 48 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 49 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 49 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 49 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 0 50 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) 1 50 tensor(1.1493e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.])

        0., 0.]) 0 38 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 39 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 42 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 43 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 43 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 43 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 44 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 44 tensor(3.3854e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 44 tensor(3.3

        0., 0.]) 0 38 tensor(9.1024e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 38 tensor(9.1024e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 38 tensor(9.3789e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 28 tensor(9.3789e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 14 tensor(9.3789e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 24 tensor(9.3789e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 21 tensor(9.3789e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 26 tensor(9.3789e-05)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 29 tensor(9.3

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 32 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 32 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 32 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 32 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 24 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 12 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 21 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]) 0 18 tensor(0.0003)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 28 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        2., 0.]) 0 27 tensor(0.0008)
tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 

tensor([1., 1., 1., 0., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 24 tensor(0.0018)
tensor([1., 1., 1., 0., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 24 tensor(0.0018)
tensor([1., 1., 1., 0., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 23 tensor(0.0019)
tensor([1., 1., 1., 0., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 17 tensor(0.0019)
tensor([1., 1., 1., 0., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 9 tensor(0.0019)
tensor([1., 1., 1., 0., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 1 15 tensor(0.0019)
tensor([1., 1., 1., 1., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 13 tensor(0.0019)
tensor([1., 1., 1., 1., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1., 1., 1., 3.,
        3., 0.]) 0 16 tensor(0.0019)
tensor([1., 1., 1., 1., 0., 0., 2., 0., 2., 0., 1., 1., 1., 1., 1

tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 21 tensor(0.0038)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 21 tensor(0.0038)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 21 tensor(0.0038)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 20 tensor(0.0038)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 20 tensor(0.0038)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 22 tensor(0.0039)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 15 tensor(0.0039)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1., 2., 3., 3.,
        4., 1.]) 0 9 tensor(0.0039)
tensor([3., 2., 1., 4., 0., 2., 3., 2., 3., 2., 7., 2., 3., 1., 1

tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 14 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 15 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 17 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 18 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 19 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 20 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.,  5.,  4.,  4., 10.,  5.,  5.,  2.,
         2.,  8.,  3.,  8.,  6.,  3.]) 0 21 tensor(0.0074)
tensor([ 6.,  6.,  2.,  7.,  0.,  3.,  5.

tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 22 tensor(0.0125)
tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 21 tensor(0.0127)
tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 17 tensor(0.0127)
tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 8 tensor(0.0127)
tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 14 tensor(0.0127)
tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 12 tensor(0.0127)
tensor([11., 12.,  4.,  9.,  2.,  5., 11., 11.,  9., 12., 15., 10., 11.,  9.,
         4., 15.,  8., 11., 11.,  6.]) 0 13 tensor(0.0127)
tensor([11., 12.,  4.,  9.,  2.,  5., 11.,

tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 18.,
        14., 28., 15., 15., 20., 14.]) 2 28 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 20.,
        14., 28., 15., 15., 20., 14.]) 0 26 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 20.,
        14., 28., 15., 15., 20., 14.]) 0 27 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 20.,
        14., 28., 15., 15., 20., 14.]) 0 28 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 20.,
        14., 28., 15., 15., 20., 14.]) 0 24 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 20.,
        14., 28., 15., 15., 20., 14.]) 0 26 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18., 19., 15., 20., 29., 17., 20., 20.,
        14., 28., 15., 15., 20., 14.]) 0 26 tensor(0.0184)
tensor([21., 25.,  7., 19.,  6., 10., 18.

tensor([34., 45., 11., 26., 23., 19., 37., 38., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 0 19 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 37., 38., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 0 23 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 37., 38., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 1 28 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 38., 38., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 1 31 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 38., 39., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 0 31 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 38., 39., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 0 34 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 38., 39., 26., 35., 50., 32., 38., 44.,
        34., 44., 37., 38., 40., 28.]) 1 25 tensor(0.0233)
tensor([34., 45., 11., 26., 23., 19., 38.

tensor([54., 59., 22., 47., 40., 34., 54., 50., 43., 52., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 0 29 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 54., 50., 43., 52., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 1 21 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 55., 50., 43., 52., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 0 25 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 55., 50., 43., 52., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 0 32 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 55., 50., 43., 52., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 1 23 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 55., 50., 43., 53., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 0 10 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 55., 50., 43., 53., 65., 56., 65., 62.,
        48., 61., 57., 54., 58., 54.]) 1 19 tensor(0.0263)
tensor([54., 59., 22., 47., 40., 34., 55.

tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 4 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 7 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 15 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 8 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 9 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 11 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61., 54., 66., 65., 67., 71., 68.,
        60., 67., 66., 64., 67., 63.]) 0 8 tensor(0.0280)
tensor([67., 64., 33., 61., 55., 58., 67., 61.

tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 8 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 6 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 4 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 7 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 8 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 3 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 67., 72., 71., 70., 74., 73.,
        69., 73., 71., 69., 72., 69.]) 0 4 tensor(0.0289)
tensor([70., 71., 48., 70., 67., 69., 71., 68., 

tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 72., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 0 5 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 72., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 0 2 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 72., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 0 4 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 72., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 0 3 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 72., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 0 4 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 72., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 1 3 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 71., 73., 73., 74., 74., 75.,
        74., 74., 72., 72., 73., 73.]) 0 2 tensor(0.0293)
tensor([73., 73., 65., 73., 70., 73., 71., 72., 

        75., 75., 75., 74., 74., 75.]) 0 1 tensor(0.0294)
tensor([75., 74., 70., 75., 72., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 0 5 tensor(0.0294)
tensor([75., 74., 70., 75., 72., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 0 0 tensor(0.0294)
tensor([75., 74., 70., 75., 72., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 1 3 tensor(0.0294)
tensor([75., 74., 70., 75., 73., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 0 2 tensor(0.0294)
tensor([75., 74., 70., 75., 73., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 0 1 tensor(0.0294)
tensor([75., 74., 70., 75., 73., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 0 2 tensor(0.0294)
tensor([75., 74., 70., 75., 73., 73., 74., 73., 73., 74., 74., 75., 74., 75.,
        75., 75., 75., 74., 74., 75.]) 0 2 tenso

        75., 75., 75., 75., 75., 75.]) 0 1 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 1 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 1 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 1 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 74., 74., 75., 74., 75., 74., 74., 75., 74., 75.,
        75., 75., 75., 75., 75., 75.]) 0 1 tenso

tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0295)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 1 tensor(0.0296)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 75., 74., 74., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 1 tensor(0.0296)
tensor([75., 74., 74., 75., 75., 74., 75., 74., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 74., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0296)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0293)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0291)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0299)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tenso

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0327)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0286)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0294)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0294)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0294)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0294)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0294)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0294)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.0323)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.

tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75., 75.,
        75., 75., 75., 75., 75., 75.]) 0 0 tensor(0.1667)
tensor([75., 75., 75., 75., 75., 75., 75., 75., 

In [48]:
reload(bu)
model, train_load, val_load = bu.main()

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


max value (train): 73
max value (val): 73
support size (train): 12
EPOCH 1:
  batch 32 loss: -0.018750008435745258
LOSS train -0.018750008435745258 valid -0.044795867055654526
EPOCH 2:
  batch 32 loss: -0.09693392110057175
LOSS train -0.09693392110057175 valid -0.07967560738325119
EPOCH 3:
  batch 32 loss: -0.14178555947728455
LOSS train -0.14178555947728455 valid -0.11542240530252457
EPOCH 4:
  batch 32 loss: -0.17942618601955473
LOSS train -0.17942618601955473 valid -0.12528419494628906
EPOCH 5:
  batch 32 loss: -0.20304140448570251
LOSS train -0.20304140448570251 valid -0.138770192861557
EPOCH 6:
  batch 32 loss: -0.21679181372746825
LOSS train -0.21679181372746825 valid -0.16617052257061005
EPOCH 7:
  batch 32 loss: -0.261158759938553
LOSS train -0.261158759938553 valid -0.17493270337581635
EPOCH 8:
  batch 32 loss: -0.23783440561965108
LOSS train -0.23783440561965108 valid -0.16854210197925568
EPOCH 9:
  batch 32 loss: -0.26310963137075305
LOSS train -0.26310963137075305 valid -0.

  batch 32 loss: -0.3253859132528305
LOSS train -0.3253859132528305 valid -0.2495686262845993
EPOCH 80:
  batch 32 loss: -0.34264075895771384
LOSS train -0.34264075895771384 valid -0.2359837293624878
EPOCH 81:
  batch 32 loss: -0.3319756928831339
LOSS train -0.3319756928831339 valid -0.3755405843257904
EPOCH 82:
  batch 32 loss: -0.30601905239745975
LOSS train -0.30601905239745975 valid -0.278226763010025
EPOCH 83:
  batch 32 loss: -0.32473467057570815
LOSS train -0.32473467057570815 valid -0.25187861919403076
EPOCH 84:
  batch 32 loss: -0.3294050367549062
LOSS train -0.3294050367549062 valid -0.27386459708213806
EPOCH 85:
  batch 32 loss: -0.3062241063453257
LOSS train -0.3062241063453257 valid -0.2647194266319275
EPOCH 86:
  batch 32 loss: -0.3442108426243067
LOSS train -0.3442108426243067 valid -0.23079200088977814
EPOCH 87:
  batch 32 loss: -0.336552148219198
LOSS train -0.336552148219198 valid -0.2963218688964844
EPOCH 88:
  batch 32 loss: -0.2993809310719371
LOSS train -0.2993809

  batch 32 loss: -0.31525111524388194
LOSS train -0.31525111524388194 valid -0.22779631614685059
EPOCH 158:
  batch 32 loss: -0.34779604664072394
LOSS train -0.34779604664072394 valid -0.24405118823051453
EPOCH 159:
  batch 32 loss: -0.31178407184779644
LOSS train -0.31178407184779644 valid -0.2670402228832245
EPOCH 160:
  batch 32 loss: -0.30549177434295416
LOSS train -0.30549177434295416 valid -0.266231894493103
EPOCH 161:
  batch 32 loss: -0.3330772826448083
LOSS train -0.3330772826448083 valid -0.262710839509964
EPOCH 162:
  batch 32 loss: -0.30567422648891807
LOSS train -0.30567422648891807 valid -0.27608877420425415
EPOCH 163:
  batch 32 loss: -0.3197634044336155
LOSS train -0.3197634044336155 valid -0.2175915539264679
EPOCH 164:
  batch 32 loss: -0.31322254007682204
LOSS train -0.31322254007682204 valid -0.2224099338054657
EPOCH 165:
  batch 32 loss: -0.3250670749694109
LOSS train -0.3250670749694109 valid -0.26570358872413635
EPOCH 166:
  batch 32 loss: -0.3175623160786927
LOSS

In [14]:
np.clip(3,0,0)

0

In [31]:
from scipy.stats import binom

In [36]:
binom.rvs(10, 1e-5, 1)

1